// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// $Rev: 5081 $
// File generated on 25.03.2009 20:57:27 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files\SCANCODE\Компонента 1С для принтеров Godex (ESC)\GodexESC.dll (1)
// LIBID: {4F0D4571-0E7B-11D1-A486-004095E1DAEA}
// LCID: 0
// Helpfile: 
// HelpString: V7 AddIn 1.0 Type Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINDOWS\system32\stdole2.tlb)
// ************************************************************************ //
#ifndef   AddInLib_OCXH
#define   AddInLib_OCXH

#pragma option push -b -w-inl

#include <olectrls.hpp>
#include <oleserver.hpp>
#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "AddInLib_TLB.h"
namespace Addinlib_tlb
{

// *********************************************************************//
// HelpString: V7 AddIn 1.0 Type Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TAddIn
// Help String      : GodexESC Class
// Default Interface: IInitDone
// Def. Intf. Object: IInitDonePtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TAddIn : public Oleserver::TOleServer
{
  IInitDonePtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TAddIn(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IInitDonePtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IInitDonePtr intf);


  void            __fastcall Init(LPDISPATCH pConnection/*[in]*/);
  void            __fastcall Done(void);
  void            __fastcall GetInfo(LPSAFEARRAY* pInfo/*[in,out]*/);
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TAddInConnection
// Help String      : AddInConnection Class
// Default Interface: IPropertyProfile
// Def. Intf. Object: IPropertyProfilePtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TAddInConnection : public Oleserver::TOleServer
{
  IPropertyProfilePtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TAddInConnection(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IPropertyProfilePtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IPropertyProfilePtr intf);


  void            __fastcall RemoteRead(LPWSTR pszPropName/*[in]*/, VARIANT* pVar/*[out]*/, 
                                        Addinlib_tlb::IErrorLog* pErrorLog/*[in]*/, 
                                        unsigned_long varType/*[in]*/, LPUNKNOWN pUnkObj/*[in]*/);
  void            __fastcall Write(LPWSTR pszPropName/*[in]*/, VARIANT* pVar/*[in]*/);
  void            __fastcall RegisterProfileAs(BSTR bstrProfileName);
};

};     // namespace Addinlib_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Addinlib_tlb;
#endif

#pragma option pop

#endif // AddInLib_OCXH
